apiVersion: v1
kind: Service
metadata:
  name: codis-dashboard
  namespace: user 
spec:
  ports:
    - name: dashboard
      port: 18087
  selector:
      app: codis-dashboard
      product: "user"
  type: NodePort
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-dashboard
  namespace: user 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: codis-dashboard
        product: "user"
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: dashboard
          image: reg.local:5000/codis-dashboard:latest
          ports:
            - containerPort: 18087
          env:
            - name: PRODUCT
              value: "user"
            - name: ZK
              value: zookeeper.default:2181
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-master-g1
  namespace: user 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: codis-master
        group: "1" 
        product: "user"
    spec:
      volumes:
       - name: data
         hostPath: 
           path: /opt/codis_data/master
      containers:
        - name: codis-master
          env:
            - name: GROUP
              value: "1"
            - name: PRODUCT
              value: "user"
          image: reg.local:5000/codis-master:latest
          volumeMounts:
             - mountPath: /mnt
               name: data 
          ports:
             - containerPort: 6380
               name: redis 
---
apiVersion: v1
kind: Service
metadata:
  name: codis-master-g1
  namespace: user 
spec:
  ports:
    - name: redis
      port: 6380
  selector:
    app: codis-master
    group: "1"
    product: "user"
---
apiVersion: v1
kind: Service
metadata:
  name: codis-slave-g1
  namespace: user 
spec:
  ports:
    - name: redis
      port: 6380
  selector:
    app: codis-slave
    group: "1"
    product: "user"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-slave-g1
  namespace: user 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: codis-slave
        group: "1" 
        product: "user"
    spec:
      volumes:
       - name: data
         hostPath: 
           path: /opt/codis_data/slave
      containers:
        - name: codis-slave
          env:
            - name:  GROUP
              value: "1"
            - name: PRODUCT
              value: "user"
          image: reg.local:5000/codis-slave:latest
          volumeMounts:
             - mountPath: /mnt
               name: data 
          ports:
             - containerPort: 6380
               name: redis 
---
apiVersion: v1
kind: Service
metadata:
  name: codis-proxy
  namespace: user 
spec:
  ports:
    - name: proxy 
      port: 19000
    - name: debug 
      port: 11000
  selector:
    app: codis-proxy
    product: "user"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: codis-proxy
  namespace: user 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: codis-proxy
        product: "user"
    spec:
      volumes:
       - name: data
         hostPath: 
           path: /opt/codis_data/proxy
      containers:
        - name: codis-proxy
          env:
            - name: PRODUCT
              value: "user"
            - name: ZK
              value: zookeeper.default:2181
          image: reg.local:5000/codis-proxy:latest
          volumeMounts:
             - mountPath: /mnt
               name: data 
          ports:
             - containerPort: 19000
               name: proxy
             - containerPort: 11000
               name: debug 
